# Generated by Django 3.2.6 on 2021-08-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0002_auto_20210825_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option_1', models.CharField(max_length=500)),
                ('option_2', models.CharField(max_length=500)),
                ('option_3', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Exam Part 1',
                'verbose_name_plural': 'Exam Part 1',
            },
        ),
        migrations.CreateModel(
            name='ExamPart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option_1', models.CharField(max_length=500)),
                ('option_2', models.CharField(max_length=500)),
                ('option_3', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Exam Part 2',
                'verbose_name_plural': 'Exam Part 2',
            },
        ),
        migrations.CreateModel(
            name='ExamPart3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option_1', models.CharField(max_length=500)),
                ('option_2', models.CharField(max_length=500)),
                ('option_3', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Exam Part 3',
                'verbose_name_plural': 'Exam Part 3',
            },
        ),
    ]
