# Generated by Django 3.2.6 on 2021-08-26 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0004_exampart3_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampart1',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/question/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exampart2',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/question/'),
            preserve_default=False,
        ),
    ]
