# Generated by Django 3.2.8 on 2021-11-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0005_auto_20210826_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='introduction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='introduction_description',
            field=models.TextField(default='SOME STRING', max_length=1000),
        ),
    ]
